# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GolbexSDK-Example-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GolbexSDK-Example-iOS
  pod 'GolbexSDK', :path => '../../../GolbexSwift'
end
